apiVersion: waf.cloudflare.upbound.io/v1alpha1
kind: Rule
metadata:
  name: example
  labels:
    testing.upbound.io/example-name: example
    testing.cloudflare.upbound.io/require-zone: "true"
spec:
  forProvider:
    zoneIdRefs:
      name: example
    ruleId: "100000"
    mode: simulate
