apiVersion: waf.cloudflare.upbound.io/v1alpha1
kind: WAFPackage
metadata:
  name: example
  labels:
    testing.upbound.io/example-name: example
    testing.cloudflare.upbound.io/require-zone: "true"
spec:
  forProvider:
    zoneIdRefs:
      name: example
    packageId: c504870194831cd12c3fc0284f294abb
    sensitivity: medium
    actionMode: simulate
