apiVersion: zone.cloudflare.upbound.io/v1alpha1
kind: Healthcheck
metadata:
  name: example-healthcheck-https
  labels:
    testing.cloudflare.upbound.io/require-zone: "true"
spec:
  forProvider:
    zoneIdRef:
      name: example
    name: "http-health-check"
    description: "example http health check"
    address: "kidp.io"
    suspended: false
    checkRegions:
      - WEU
      - EEU
    type: "HTTPS"
    port: 443
    method: "GET"
    path: "/health"
    expectedBody: "alive"
    expectedCodes:
      - "2xx"
      - "301"
    followRedirects: true
    allowInsecure: false
    header:
      - header: "Host"
        values:
          - "kidp.io"
    timeout: 10
    retries: 2
    interval: 60
    consecutiveFails: 3
    consecutiveSuccesses: 2

---
apiVersion: zone.cloudflare.upbound.io/v1alpha1
kind: Healthcheck
metadata:
  name: example-healthcheck-tcp
  labels:
    testing.cloudflare.upbound.io/require-zone: "true"
spec:
  forProvider:
    zoneIdRef:
      name: example
    name: "tcp-health-check"
    description: "example tcp health check"
    address: "kidp.io"
    suspended: false
    checkRegions:
      - "WEU"
      - "EEU"
    type: "TCP"
    port: 22
    method: "connection_established"
    timeout: 10
    retries: 2
    interval: 60
    consecutiveFails: 3
    consecutiveSuccesses: 2
