apiVersion: zone.cloudflare.upbound.io/v1alpha1
kind: TotalTLS
metadata:
  name: example-tired-cache
  labels:
    testing.cloudflare.upbound.io/require-zone: "true"
spec:
  forProvider:
    zoneIdRef:
      name: example
    enabled: true
    certificateAuthority: lets_encrypt
