apiVersion: zone.cloudflare.upbound.io/v1alpha1
kind: Zone
metadata:
  name: example
  labels:
    testing.upbound.io/example-name: example
    cloudflare-zone: zone
spec:
  forProvider:
    zone: cloudflare-test.crossplane.io
