apiVersion: zone.cloudflare.upbound.io/v1alpha1
kind: Zone
metadata:
  name: example
  labels:
    testing.upbound.io/example-name: example
    cloudflare-zone: zone
  annotations:
    uptest.upbound.io/pre-delete-hook: ../../cluster/test/cleanup-children.sh zone
spec:
  forProvider:
    zone: kidp.io
