/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BookmarkObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type BookmarkParameters struct {

	// The account identifier to target for the resource. Conflicts with `zone_id`.
	// +crossplane:generate:reference:type=github.com/cdloh/provider-cloudflare/apis/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// Option to show/hide the bookmark in the app launcher. Defaults to `true`.
	// +kubebuilder:validation:Optional
	AppLauncherVisible *bool `json:"appLauncherVisible,omitempty" tf:"app_launcher_visible,omitempty"`

	// The domain of the bookmark application. Can include subdomains, paths, or both.
	// +kubebuilder:validation:Required
	Domain *string `json:"domain" tf:"domain,omitempty"`

	// The image URL for the logo shown in the app launcher dashboard.
	// +kubebuilder:validation:Optional
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// Name of the bookmark application.
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// The zone identifier to target for the resource. Conflicts with `account_id`.
	// +crossplane:generate:reference:type=github.com/cdloh/provider-cloudflare/apis/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// BookmarkSpec defines the desired state of Bookmark
type BookmarkSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BookmarkParameters `json:"forProvider"`
}

// BookmarkStatus defines the observed state of Bookmark.
type BookmarkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BookmarkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Bookmark is the Schema for the Bookmarks API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type Bookmark struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BookmarkSpec   `json:"spec"`
	Status            BookmarkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BookmarkList contains a list of Bookmarks
type BookmarkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Bookmark `json:"items"`
}

// Repository type metadata.
var (
	Bookmark_Kind             = "Bookmark"
	Bookmark_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Bookmark_Kind}.String()
	Bookmark_KindAPIVersion   = Bookmark_Kind + "." + CRDGroupVersion.String()
	Bookmark_GroupVersionKind = CRDGroupVersion.WithKind(Bookmark_Kind)
)

func init() {
	SchemeBuilder.Register(&Bookmark{}, &BookmarkList{})
}
