apiVersion: zone.cloudflare.upbound.io/v1alpha1
kind: TotalTLS
metadata:
  annotations:
    meta.upbound.io/example-id: zone/v1alpha1/totaltls
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    certificateAuthority: lets_encrypt
    enabled: true
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
