apiVersion: zone.cloudflare.upbound.io/v1alpha1
kind: URLNormalizationSettings
metadata:
  annotations:
    meta.upbound.io/example-id: zone/v1alpha1/urlnormalizationsettings
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    scope: incoming
    type: cloudflare
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
