apiVersion: filters.cloudflare.upbound.io/v1alpha1
kind: Filter
metadata:
  name: example-firewall-rule-filter
  labels:
    testing.cloudflare.upbound.io/require-zone: "true"
spec:
  forProvider:
    zoneIdRef:
      name: example
    description: Wordpress break-in attempts that are outside of the office
    expression: "(http.request.uri.path ~ \".*wp-login.php\" or http.request.uri.path ~ \".*xmlrpc.php\") and ip.src ne 192.0.2.1"

---
apiVersion: firewall.cloudflare.upbound.io/v1alpha1
kind: Rule
metadata:
  name: example-firewall-rule
  labels:
    testing.cloudflare.upbound.io/require-zone: "true"
spec:
  forProvider:
    zoneIdRef:
      name: example
    description: Block wordpress break-in attempts
    filterIdRef:
      name: example-firewall-rule-filter
    action: block
