apiVersion: access.cloudflare.upbound.io/v1alpha1
kind: CACertificate
metadata:
  annotations:
    meta.upbound.io/example-id: access/v1alpha1/cacertificate
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
