//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigInitParameters) DeepCopyInto(out *ConfigInitParameters) {
	*out = *in
	if in.APIURL != nil {
		in, out := &in.APIURL, &out.APIURL
		*out = new(string)
		**out = **in
	}
	if in.AuthURL != nil {
		in, out := &in.AuthURL, &out.AuthURL
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.CustomerID != nil {
		in, out := &in.CustomerID, &out.CustomerID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigInitParameters.
func (in *ConfigInitParameters) DeepCopy() *ConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigObservation) DeepCopyInto(out *ConfigObservation) {
	*out = *in
	if in.APIURL != nil {
		in, out := &in.APIURL, &out.APIURL
		*out = new(string)
		**out = **in
	}
	if in.AuthURL != nil {
		in, out := &in.AuthURL, &out.AuthURL
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.CustomerID != nil {
		in, out := &in.CustomerID, &out.CustomerID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigObservation.
func (in *ConfigObservation) DeepCopy() *ConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigParameters) DeepCopyInto(out *ConfigParameters) {
	*out = *in
	if in.APIURL != nil {
		in, out := &in.APIURL, &out.APIURL
		*out = new(string)
		**out = **in
	}
	if in.AuthURL != nil {
		in, out := &in.AuthURL, &out.AuthURL
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientKeySecretRef != nil {
		in, out := &in.ClientKeySecretRef, &out.ClientKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.ClientSecretSecretRef != nil {
		in, out := &in.ClientSecretSecretRef, &out.ClientSecretSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.CustomerID != nil {
		in, out := &in.CustomerID, &out.CustomerID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigParameters.
func (in *ConfigParameters) DeepCopy() *ConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePolicyCertificates) DeepCopyInto(out *DevicePolicyCertificates) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePolicyCertificates.
func (in *DevicePolicyCertificates) DeepCopy() *DevicePolicyCertificates {
	if in == nil {
		return nil
	}
	out := new(DevicePolicyCertificates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevicePolicyCertificates) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePolicyCertificatesInitParameters) DeepCopyInto(out *DevicePolicyCertificatesInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePolicyCertificatesInitParameters.
func (in *DevicePolicyCertificatesInitParameters) DeepCopy() *DevicePolicyCertificatesInitParameters {
	if in == nil {
		return nil
	}
	out := new(DevicePolicyCertificatesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePolicyCertificatesList) DeepCopyInto(out *DevicePolicyCertificatesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevicePolicyCertificates, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePolicyCertificatesList.
func (in *DevicePolicyCertificatesList) DeepCopy() *DevicePolicyCertificatesList {
	if in == nil {
		return nil
	}
	out := new(DevicePolicyCertificatesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevicePolicyCertificatesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePolicyCertificatesObservation) DeepCopyInto(out *DevicePolicyCertificatesObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePolicyCertificatesObservation.
func (in *DevicePolicyCertificatesObservation) DeepCopy() *DevicePolicyCertificatesObservation {
	if in == nil {
		return nil
	}
	out := new(DevicePolicyCertificatesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePolicyCertificatesParameters) DeepCopyInto(out *DevicePolicyCertificatesParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneIDRef != nil {
		in, out := &in.ZoneIDRef, &out.ZoneIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ZoneIDSelector != nil {
		in, out := &in.ZoneIDSelector, &out.ZoneIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePolicyCertificatesParameters.
func (in *DevicePolicyCertificatesParameters) DeepCopy() *DevicePolicyCertificatesParameters {
	if in == nil {
		return nil
	}
	out := new(DevicePolicyCertificatesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePolicyCertificatesSpec) DeepCopyInto(out *DevicePolicyCertificatesSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePolicyCertificatesSpec.
func (in *DevicePolicyCertificatesSpec) DeepCopy() *DevicePolicyCertificatesSpec {
	if in == nil {
		return nil
	}
	out := new(DevicePolicyCertificatesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePolicyCertificatesStatus) DeepCopyInto(out *DevicePolicyCertificatesStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePolicyCertificatesStatus.
func (in *DevicePolicyCertificatesStatus) DeepCopy() *DevicePolicyCertificatesStatus {
	if in == nil {
		return nil
	}
	out := new(DevicePolicyCertificatesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureIntegration) DeepCopyInto(out *DevicePostureIntegration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureIntegration.
func (in *DevicePostureIntegration) DeepCopy() *DevicePostureIntegration {
	if in == nil {
		return nil
	}
	out := new(DevicePostureIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevicePostureIntegration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureIntegrationInitParameters) DeepCopyInto(out *DevicePostureIntegrationInitParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureIntegrationInitParameters.
func (in *DevicePostureIntegrationInitParameters) DeepCopy() *DevicePostureIntegrationInitParameters {
	if in == nil {
		return nil
	}
	out := new(DevicePostureIntegrationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureIntegrationList) DeepCopyInto(out *DevicePostureIntegrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevicePostureIntegration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureIntegrationList.
func (in *DevicePostureIntegrationList) DeepCopy() *DevicePostureIntegrationList {
	if in == nil {
		return nil
	}
	out := new(DevicePostureIntegrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevicePostureIntegrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureIntegrationObservation) DeepCopyInto(out *DevicePostureIntegrationObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureIntegrationObservation.
func (in *DevicePostureIntegrationObservation) DeepCopy() *DevicePostureIntegrationObservation {
	if in == nil {
		return nil
	}
	out := new(DevicePostureIntegrationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureIntegrationParameters) DeepCopyInto(out *DevicePostureIntegrationParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.AccountIDRef != nil {
		in, out := &in.AccountIDRef, &out.AccountIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AccountIDSelector != nil {
		in, out := &in.AccountIDSelector, &out.AccountIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureIntegrationParameters.
func (in *DevicePostureIntegrationParameters) DeepCopy() *DevicePostureIntegrationParameters {
	if in == nil {
		return nil
	}
	out := new(DevicePostureIntegrationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureIntegrationSpec) DeepCopyInto(out *DevicePostureIntegrationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureIntegrationSpec.
func (in *DevicePostureIntegrationSpec) DeepCopy() *DevicePostureIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(DevicePostureIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureIntegrationStatus) DeepCopyInto(out *DevicePostureIntegrationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureIntegrationStatus.
func (in *DevicePostureIntegrationStatus) DeepCopy() *DevicePostureIntegrationStatus {
	if in == nil {
		return nil
	}
	out := new(DevicePostureIntegrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureRule) DeepCopyInto(out *DevicePostureRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureRule.
func (in *DevicePostureRule) DeepCopy() *DevicePostureRule {
	if in == nil {
		return nil
	}
	out := new(DevicePostureRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevicePostureRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureRuleInitParameters) DeepCopyInto(out *DevicePostureRuleInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expiration != nil {
		in, out := &in.Expiration, &out.Expiration
		*out = new(string)
		**out = **in
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make([]InputInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]MatchInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureRuleInitParameters.
func (in *DevicePostureRuleInitParameters) DeepCopy() *DevicePostureRuleInitParameters {
	if in == nil {
		return nil
	}
	out := new(DevicePostureRuleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureRuleList) DeepCopyInto(out *DevicePostureRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevicePostureRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureRuleList.
func (in *DevicePostureRuleList) DeepCopy() *DevicePostureRuleList {
	if in == nil {
		return nil
	}
	out := new(DevicePostureRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevicePostureRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureRuleObservation) DeepCopyInto(out *DevicePostureRuleObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expiration != nil {
		in, out := &in.Expiration, &out.Expiration
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make([]InputObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]MatchObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureRuleObservation.
func (in *DevicePostureRuleObservation) DeepCopy() *DevicePostureRuleObservation {
	if in == nil {
		return nil
	}
	out := new(DevicePostureRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureRuleParameters) DeepCopyInto(out *DevicePostureRuleParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.AccountIDRef != nil {
		in, out := &in.AccountIDRef, &out.AccountIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AccountIDSelector != nil {
		in, out := &in.AccountIDSelector, &out.AccountIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expiration != nil {
		in, out := &in.Expiration, &out.Expiration
		*out = new(string)
		**out = **in
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make([]InputParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]MatchParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureRuleParameters.
func (in *DevicePostureRuleParameters) DeepCopy() *DevicePostureRuleParameters {
	if in == nil {
		return nil
	}
	out := new(DevicePostureRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureRuleSpec) DeepCopyInto(out *DevicePostureRuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureRuleSpec.
func (in *DevicePostureRuleSpec) DeepCopy() *DevicePostureRuleSpec {
	if in == nil {
		return nil
	}
	out := new(DevicePostureRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureRuleStatus) DeepCopyInto(out *DevicePostureRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureRuleStatus.
func (in *DevicePostureRuleStatus) DeepCopy() *DevicePostureRuleStatus {
	if in == nil {
		return nil
	}
	out := new(DevicePostureRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSettingsPolicy) DeepCopyInto(out *DeviceSettingsPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSettingsPolicy.
func (in *DeviceSettingsPolicy) DeepCopy() *DeviceSettingsPolicy {
	if in == nil {
		return nil
	}
	out := new(DeviceSettingsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceSettingsPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSettingsPolicyInitParameters) DeepCopyInto(out *DeviceSettingsPolicyInitParameters) {
	*out = *in
	if in.AllowModeSwitch != nil {
		in, out := &in.AllowModeSwitch, &out.AllowModeSwitch
		*out = new(bool)
		**out = **in
	}
	if in.AllowUpdates != nil {
		in, out := &in.AllowUpdates, &out.AllowUpdates
		*out = new(bool)
		**out = **in
	}
	if in.AllowedToLeave != nil {
		in, out := &in.AllowedToLeave, &out.AllowedToLeave
		*out = new(bool)
		**out = **in
	}
	if in.AutoConnect != nil {
		in, out := &in.AutoConnect, &out.AutoConnect
		*out = new(float64)
		**out = **in
	}
	if in.CaptivePortal != nil {
		in, out := &in.CaptivePortal, &out.CaptivePortal
		*out = new(float64)
		**out = **in
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisableAutoFallback != nil {
		in, out := &in.DisableAutoFallback, &out.DisableAutoFallback
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeOfficeIps != nil {
		in, out := &in.ExcludeOfficeIps, &out.ExcludeOfficeIps
		*out = new(bool)
		**out = **in
	}
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Precedence != nil {
		in, out := &in.Precedence, &out.Precedence
		*out = new(float64)
		**out = **in
	}
	if in.ServiceModeV2Mode != nil {
		in, out := &in.ServiceModeV2Mode, &out.ServiceModeV2Mode
		*out = new(string)
		**out = **in
	}
	if in.ServiceModeV2Port != nil {
		in, out := &in.ServiceModeV2Port, &out.ServiceModeV2Port
		*out = new(float64)
		**out = **in
	}
	if in.SupportURL != nil {
		in, out := &in.SupportURL, &out.SupportURL
		*out = new(string)
		**out = **in
	}
	if in.SwitchLocked != nil {
		in, out := &in.SwitchLocked, &out.SwitchLocked
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSettingsPolicyInitParameters.
func (in *DeviceSettingsPolicyInitParameters) DeepCopy() *DeviceSettingsPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(DeviceSettingsPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSettingsPolicyList) DeepCopyInto(out *DeviceSettingsPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeviceSettingsPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSettingsPolicyList.
func (in *DeviceSettingsPolicyList) DeepCopy() *DeviceSettingsPolicyList {
	if in == nil {
		return nil
	}
	out := new(DeviceSettingsPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceSettingsPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSettingsPolicyObservation) DeepCopyInto(out *DeviceSettingsPolicyObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.AllowModeSwitch != nil {
		in, out := &in.AllowModeSwitch, &out.AllowModeSwitch
		*out = new(bool)
		**out = **in
	}
	if in.AllowUpdates != nil {
		in, out := &in.AllowUpdates, &out.AllowUpdates
		*out = new(bool)
		**out = **in
	}
	if in.AllowedToLeave != nil {
		in, out := &in.AllowedToLeave, &out.AllowedToLeave
		*out = new(bool)
		**out = **in
	}
	if in.AutoConnect != nil {
		in, out := &in.AutoConnect, &out.AutoConnect
		*out = new(float64)
		**out = **in
	}
	if in.CaptivePortal != nil {
		in, out := &in.CaptivePortal, &out.CaptivePortal
		*out = new(float64)
		**out = **in
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisableAutoFallback != nil {
		in, out := &in.DisableAutoFallback, &out.DisableAutoFallback
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeOfficeIps != nil {
		in, out := &in.ExcludeOfficeIps, &out.ExcludeOfficeIps
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Precedence != nil {
		in, out := &in.Precedence, &out.Precedence
		*out = new(float64)
		**out = **in
	}
	if in.ServiceModeV2Mode != nil {
		in, out := &in.ServiceModeV2Mode, &out.ServiceModeV2Mode
		*out = new(string)
		**out = **in
	}
	if in.ServiceModeV2Port != nil {
		in, out := &in.ServiceModeV2Port, &out.ServiceModeV2Port
		*out = new(float64)
		**out = **in
	}
	if in.SupportURL != nil {
		in, out := &in.SupportURL, &out.SupportURL
		*out = new(string)
		**out = **in
	}
	if in.SwitchLocked != nil {
		in, out := &in.SwitchLocked, &out.SwitchLocked
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSettingsPolicyObservation.
func (in *DeviceSettingsPolicyObservation) DeepCopy() *DeviceSettingsPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(DeviceSettingsPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSettingsPolicyParameters) DeepCopyInto(out *DeviceSettingsPolicyParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.AccountIDRef != nil {
		in, out := &in.AccountIDRef, &out.AccountIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AccountIDSelector != nil {
		in, out := &in.AccountIDSelector, &out.AccountIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowModeSwitch != nil {
		in, out := &in.AllowModeSwitch, &out.AllowModeSwitch
		*out = new(bool)
		**out = **in
	}
	if in.AllowUpdates != nil {
		in, out := &in.AllowUpdates, &out.AllowUpdates
		*out = new(bool)
		**out = **in
	}
	if in.AllowedToLeave != nil {
		in, out := &in.AllowedToLeave, &out.AllowedToLeave
		*out = new(bool)
		**out = **in
	}
	if in.AutoConnect != nil {
		in, out := &in.AutoConnect, &out.AutoConnect
		*out = new(float64)
		**out = **in
	}
	if in.CaptivePortal != nil {
		in, out := &in.CaptivePortal, &out.CaptivePortal
		*out = new(float64)
		**out = **in
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisableAutoFallback != nil {
		in, out := &in.DisableAutoFallback, &out.DisableAutoFallback
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeOfficeIps != nil {
		in, out := &in.ExcludeOfficeIps, &out.ExcludeOfficeIps
		*out = new(bool)
		**out = **in
	}
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Precedence != nil {
		in, out := &in.Precedence, &out.Precedence
		*out = new(float64)
		**out = **in
	}
	if in.ServiceModeV2Mode != nil {
		in, out := &in.ServiceModeV2Mode, &out.ServiceModeV2Mode
		*out = new(string)
		**out = **in
	}
	if in.ServiceModeV2Port != nil {
		in, out := &in.ServiceModeV2Port, &out.ServiceModeV2Port
		*out = new(float64)
		**out = **in
	}
	if in.SupportURL != nil {
		in, out := &in.SupportURL, &out.SupportURL
		*out = new(string)
		**out = **in
	}
	if in.SwitchLocked != nil {
		in, out := &in.SwitchLocked, &out.SwitchLocked
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSettingsPolicyParameters.
func (in *DeviceSettingsPolicyParameters) DeepCopy() *DeviceSettingsPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(DeviceSettingsPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSettingsPolicySpec) DeepCopyInto(out *DeviceSettingsPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSettingsPolicySpec.
func (in *DeviceSettingsPolicySpec) DeepCopy() *DeviceSettingsPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DeviceSettingsPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSettingsPolicyStatus) DeepCopyInto(out *DeviceSettingsPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSettingsPolicyStatus.
func (in *DeviceSettingsPolicyStatus) DeepCopy() *DeviceSettingsPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceSettingsPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainsInitParameters) DeepCopyInto(out *DomainsInitParameters) {
	*out = *in
	if in.DNSServer != nil {
		in, out := &in.DNSServer, &out.DNSServer
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Suffix != nil {
		in, out := &in.Suffix, &out.Suffix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainsInitParameters.
func (in *DomainsInitParameters) DeepCopy() *DomainsInitParameters {
	if in == nil {
		return nil
	}
	out := new(DomainsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainsObservation) DeepCopyInto(out *DomainsObservation) {
	*out = *in
	if in.DNSServer != nil {
		in, out := &in.DNSServer, &out.DNSServer
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Suffix != nil {
		in, out := &in.Suffix, &out.Suffix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainsObservation.
func (in *DomainsObservation) DeepCopy() *DomainsObservation {
	if in == nil {
		return nil
	}
	out := new(DomainsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainsParameters) DeepCopyInto(out *DomainsParameters) {
	*out = *in
	if in.DNSServer != nil {
		in, out := &in.DNSServer, &out.DNSServer
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Suffix != nil {
		in, out := &in.Suffix, &out.Suffix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainsParameters.
func (in *DomainsParameters) DeepCopy() *DomainsParameters {
	if in == nil {
		return nil
	}
	out := new(DomainsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackDomain) DeepCopyInto(out *FallbackDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackDomain.
func (in *FallbackDomain) DeepCopy() *FallbackDomain {
	if in == nil {
		return nil
	}
	out := new(FallbackDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FallbackDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackDomainInitParameters) DeepCopyInto(out *FallbackDomainInitParameters) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]DomainsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackDomainInitParameters.
func (in *FallbackDomainInitParameters) DeepCopy() *FallbackDomainInitParameters {
	if in == nil {
		return nil
	}
	out := new(FallbackDomainInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackDomainList) DeepCopyInto(out *FallbackDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FallbackDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackDomainList.
func (in *FallbackDomainList) DeepCopy() *FallbackDomainList {
	if in == nil {
		return nil
	}
	out := new(FallbackDomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FallbackDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackDomainObservation) DeepCopyInto(out *FallbackDomainObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]DomainsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PolicyID != nil {
		in, out := &in.PolicyID, &out.PolicyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackDomainObservation.
func (in *FallbackDomainObservation) DeepCopy() *FallbackDomainObservation {
	if in == nil {
		return nil
	}
	out := new(FallbackDomainObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackDomainParameters) DeepCopyInto(out *FallbackDomainParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.AccountIDRef != nil {
		in, out := &in.AccountIDRef, &out.AccountIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AccountIDSelector != nil {
		in, out := &in.AccountIDSelector, &out.AccountIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]DomainsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicyID != nil {
		in, out := &in.PolicyID, &out.PolicyID
		*out = new(string)
		**out = **in
	}
	if in.PolicyIDRef != nil {
		in, out := &in.PolicyIDRef, &out.PolicyIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.PolicyIDSelector != nil {
		in, out := &in.PolicyIDSelector, &out.PolicyIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackDomainParameters.
func (in *FallbackDomainParameters) DeepCopy() *FallbackDomainParameters {
	if in == nil {
		return nil
	}
	out := new(FallbackDomainParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackDomainSpec) DeepCopyInto(out *FallbackDomainSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackDomainSpec.
func (in *FallbackDomainSpec) DeepCopy() *FallbackDomainSpec {
	if in == nil {
		return nil
	}
	out := new(FallbackDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackDomainStatus) DeepCopyInto(out *FallbackDomainStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackDomainStatus.
func (in *FallbackDomainStatus) DeepCopy() *FallbackDomainStatus {
	if in == nil {
		return nil
	}
	out := new(FallbackDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputInitParameters) DeepCopyInto(out *InputInitParameters) {
	*out = *in
	if in.ActiveThreats != nil {
		in, out := &in.ActiveThreats, &out.ActiveThreats
		*out = new(float64)
		**out = **in
	}
	if in.CertificateID != nil {
		in, out := &in.CertificateID, &out.CertificateID
		*out = new(string)
		**out = **in
	}
	if in.CheckDisks != nil {
		in, out := &in.CheckDisks, &out.CheckDisks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Cn != nil {
		in, out := &in.Cn, &out.Cn
		*out = new(string)
		**out = **in
	}
	if in.ComplianceStatus != nil {
		in, out := &in.ComplianceStatus, &out.ComplianceStatus
		*out = new(string)
		**out = **in
	}
	if in.ConnectionID != nil {
		in, out := &in.ConnectionID, &out.ConnectionID
		*out = new(string)
		**out = **in
	}
	if in.CountOperator != nil {
		in, out := &in.CountOperator, &out.CountOperator
		*out = new(string)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.EidLastSeen != nil {
		in, out := &in.EidLastSeen, &out.EidLastSeen
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Exists != nil {
		in, out := &in.Exists, &out.Exists
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Infected != nil {
		in, out := &in.Infected, &out.Infected
		*out = new(bool)
		**out = **in
	}
	if in.IsActive != nil {
		in, out := &in.IsActive, &out.IsActive
		*out = new(bool)
		**out = **in
	}
	if in.IssueCount != nil {
		in, out := &in.IssueCount, &out.IssueCount
		*out = new(string)
		**out = **in
	}
	if in.NetworkStatus != nil {
		in, out := &in.NetworkStatus, &out.NetworkStatus
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Os != nil {
		in, out := &in.Os, &out.Os
		*out = new(string)
		**out = **in
	}
	if in.OsDistroName != nil {
		in, out := &in.OsDistroName, &out.OsDistroName
		*out = new(string)
		**out = **in
	}
	if in.OsDistroRevision != nil {
		in, out := &in.OsDistroRevision, &out.OsDistroRevision
		*out = new(string)
		**out = **in
	}
	if in.Overall != nil {
		in, out := &in.Overall, &out.Overall
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.RequireAll != nil {
		in, out := &in.RequireAll, &out.RequireAll
		*out = new(bool)
		**out = **in
	}
	if in.RiskLevel != nil {
		in, out := &in.RiskLevel, &out.RiskLevel
		*out = new(string)
		**out = **in
	}
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(bool)
		**out = **in
	}
	if in.SensorConfig != nil {
		in, out := &in.SensorConfig, &out.SensorConfig
		*out = new(string)
		**out = **in
	}
	if in.Sha256 != nil {
		in, out := &in.Sha256, &out.Sha256
		*out = new(string)
		**out = **in
	}
	if in.Thumbprint != nil {
		in, out := &in.Thumbprint, &out.Thumbprint
		*out = new(string)
		**out = **in
	}
	if in.TotalScore != nil {
		in, out := &in.TotalScore, &out.TotalScore
		*out = new(float64)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.VersionOperator != nil {
		in, out := &in.VersionOperator, &out.VersionOperator
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputInitParameters.
func (in *InputInitParameters) DeepCopy() *InputInitParameters {
	if in == nil {
		return nil
	}
	out := new(InputInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputObservation) DeepCopyInto(out *InputObservation) {
	*out = *in
	if in.ActiveThreats != nil {
		in, out := &in.ActiveThreats, &out.ActiveThreats
		*out = new(float64)
		**out = **in
	}
	if in.CertificateID != nil {
		in, out := &in.CertificateID, &out.CertificateID
		*out = new(string)
		**out = **in
	}
	if in.CheckDisks != nil {
		in, out := &in.CheckDisks, &out.CheckDisks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Cn != nil {
		in, out := &in.Cn, &out.Cn
		*out = new(string)
		**out = **in
	}
	if in.ComplianceStatus != nil {
		in, out := &in.ComplianceStatus, &out.ComplianceStatus
		*out = new(string)
		**out = **in
	}
	if in.ConnectionID != nil {
		in, out := &in.ConnectionID, &out.ConnectionID
		*out = new(string)
		**out = **in
	}
	if in.CountOperator != nil {
		in, out := &in.CountOperator, &out.CountOperator
		*out = new(string)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.EidLastSeen != nil {
		in, out := &in.EidLastSeen, &out.EidLastSeen
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Exists != nil {
		in, out := &in.Exists, &out.Exists
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Infected != nil {
		in, out := &in.Infected, &out.Infected
		*out = new(bool)
		**out = **in
	}
	if in.IsActive != nil {
		in, out := &in.IsActive, &out.IsActive
		*out = new(bool)
		**out = **in
	}
	if in.IssueCount != nil {
		in, out := &in.IssueCount, &out.IssueCount
		*out = new(string)
		**out = **in
	}
	if in.NetworkStatus != nil {
		in, out := &in.NetworkStatus, &out.NetworkStatus
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Os != nil {
		in, out := &in.Os, &out.Os
		*out = new(string)
		**out = **in
	}
	if in.OsDistroName != nil {
		in, out := &in.OsDistroName, &out.OsDistroName
		*out = new(string)
		**out = **in
	}
	if in.OsDistroRevision != nil {
		in, out := &in.OsDistroRevision, &out.OsDistroRevision
		*out = new(string)
		**out = **in
	}
	if in.Overall != nil {
		in, out := &in.Overall, &out.Overall
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.RequireAll != nil {
		in, out := &in.RequireAll, &out.RequireAll
		*out = new(bool)
		**out = **in
	}
	if in.RiskLevel != nil {
		in, out := &in.RiskLevel, &out.RiskLevel
		*out = new(string)
		**out = **in
	}
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(bool)
		**out = **in
	}
	if in.SensorConfig != nil {
		in, out := &in.SensorConfig, &out.SensorConfig
		*out = new(string)
		**out = **in
	}
	if in.Sha256 != nil {
		in, out := &in.Sha256, &out.Sha256
		*out = new(string)
		**out = **in
	}
	if in.Thumbprint != nil {
		in, out := &in.Thumbprint, &out.Thumbprint
		*out = new(string)
		**out = **in
	}
	if in.TotalScore != nil {
		in, out := &in.TotalScore, &out.TotalScore
		*out = new(float64)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.VersionOperator != nil {
		in, out := &in.VersionOperator, &out.VersionOperator
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputObservation.
func (in *InputObservation) DeepCopy() *InputObservation {
	if in == nil {
		return nil
	}
	out := new(InputObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputParameters) DeepCopyInto(out *InputParameters) {
	*out = *in
	if in.ActiveThreats != nil {
		in, out := &in.ActiveThreats, &out.ActiveThreats
		*out = new(float64)
		**out = **in
	}
	if in.CertificateID != nil {
		in, out := &in.CertificateID, &out.CertificateID
		*out = new(string)
		**out = **in
	}
	if in.CheckDisks != nil {
		in, out := &in.CheckDisks, &out.CheckDisks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Cn != nil {
		in, out := &in.Cn, &out.Cn
		*out = new(string)
		**out = **in
	}
	if in.ComplianceStatus != nil {
		in, out := &in.ComplianceStatus, &out.ComplianceStatus
		*out = new(string)
		**out = **in
	}
	if in.ConnectionID != nil {
		in, out := &in.ConnectionID, &out.ConnectionID
		*out = new(string)
		**out = **in
	}
	if in.CountOperator != nil {
		in, out := &in.CountOperator, &out.CountOperator
		*out = new(string)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.EidLastSeen != nil {
		in, out := &in.EidLastSeen, &out.EidLastSeen
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Exists != nil {
		in, out := &in.Exists, &out.Exists
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Infected != nil {
		in, out := &in.Infected, &out.Infected
		*out = new(bool)
		**out = **in
	}
	if in.IsActive != nil {
		in, out := &in.IsActive, &out.IsActive
		*out = new(bool)
		**out = **in
	}
	if in.IssueCount != nil {
		in, out := &in.IssueCount, &out.IssueCount
		*out = new(string)
		**out = **in
	}
	if in.NetworkStatus != nil {
		in, out := &in.NetworkStatus, &out.NetworkStatus
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Os != nil {
		in, out := &in.Os, &out.Os
		*out = new(string)
		**out = **in
	}
	if in.OsDistroName != nil {
		in, out := &in.OsDistroName, &out.OsDistroName
		*out = new(string)
		**out = **in
	}
	if in.OsDistroRevision != nil {
		in, out := &in.OsDistroRevision, &out.OsDistroRevision
		*out = new(string)
		**out = **in
	}
	if in.Overall != nil {
		in, out := &in.Overall, &out.Overall
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.RequireAll != nil {
		in, out := &in.RequireAll, &out.RequireAll
		*out = new(bool)
		**out = **in
	}
	if in.RiskLevel != nil {
		in, out := &in.RiskLevel, &out.RiskLevel
		*out = new(string)
		**out = **in
	}
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(bool)
		**out = **in
	}
	if in.SensorConfig != nil {
		in, out := &in.SensorConfig, &out.SensorConfig
		*out = new(string)
		**out = **in
	}
	if in.Sha256 != nil {
		in, out := &in.Sha256, &out.Sha256
		*out = new(string)
		**out = **in
	}
	if in.Thumbprint != nil {
		in, out := &in.Thumbprint, &out.Thumbprint
		*out = new(string)
		**out = **in
	}
	if in.TotalScore != nil {
		in, out := &in.TotalScore, &out.TotalScore
		*out = new(float64)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.VersionOperator != nil {
		in, out := &in.VersionOperator, &out.VersionOperator
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputParameters.
func (in *InputParameters) DeepCopy() *InputParameters {
	if in == nil {
		return nil
	}
	out := new(InputParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchInitParameters) DeepCopyInto(out *MatchInitParameters) {
	*out = *in
	if in.Platform != nil {
		in, out := &in.Platform, &out.Platform
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchInitParameters.
func (in *MatchInitParameters) DeepCopy() *MatchInitParameters {
	if in == nil {
		return nil
	}
	out := new(MatchInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchObservation) DeepCopyInto(out *MatchObservation) {
	*out = *in
	if in.Platform != nil {
		in, out := &in.Platform, &out.Platform
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchObservation.
func (in *MatchObservation) DeepCopy() *MatchObservation {
	if in == nil {
		return nil
	}
	out := new(MatchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchParameters) DeepCopyInto(out *MatchParameters) {
	*out = *in
	if in.Platform != nil {
		in, out := &in.Platform, &out.Platform
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchParameters.
func (in *MatchParameters) DeepCopy() *MatchParameters {
	if in == nil {
		return nil
	}
	out := new(MatchParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitTunnel) DeepCopyInto(out *SplitTunnel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitTunnel.
func (in *SplitTunnel) DeepCopy() *SplitTunnel {
	if in == nil {
		return nil
	}
	out := new(SplitTunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SplitTunnel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitTunnelInitParameters) DeepCopyInto(out *SplitTunnelInitParameters) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Tunnels != nil {
		in, out := &in.Tunnels, &out.Tunnels
		*out = make([]TunnelsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitTunnelInitParameters.
func (in *SplitTunnelInitParameters) DeepCopy() *SplitTunnelInitParameters {
	if in == nil {
		return nil
	}
	out := new(SplitTunnelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitTunnelList) DeepCopyInto(out *SplitTunnelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SplitTunnel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitTunnelList.
func (in *SplitTunnelList) DeepCopy() *SplitTunnelList {
	if in == nil {
		return nil
	}
	out := new(SplitTunnelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SplitTunnelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitTunnelObservation) DeepCopyInto(out *SplitTunnelObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.PolicyID != nil {
		in, out := &in.PolicyID, &out.PolicyID
		*out = new(string)
		**out = **in
	}
	if in.Tunnels != nil {
		in, out := &in.Tunnels, &out.Tunnels
		*out = make([]TunnelsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitTunnelObservation.
func (in *SplitTunnelObservation) DeepCopy() *SplitTunnelObservation {
	if in == nil {
		return nil
	}
	out := new(SplitTunnelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitTunnelParameters) DeepCopyInto(out *SplitTunnelParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.AccountIDRef != nil {
		in, out := &in.AccountIDRef, &out.AccountIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AccountIDSelector != nil {
		in, out := &in.AccountIDSelector, &out.AccountIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.PolicyID != nil {
		in, out := &in.PolicyID, &out.PolicyID
		*out = new(string)
		**out = **in
	}
	if in.PolicyIDRef != nil {
		in, out := &in.PolicyIDRef, &out.PolicyIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.PolicyIDSelector != nil {
		in, out := &in.PolicyIDSelector, &out.PolicyIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tunnels != nil {
		in, out := &in.Tunnels, &out.Tunnels
		*out = make([]TunnelsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitTunnelParameters.
func (in *SplitTunnelParameters) DeepCopy() *SplitTunnelParameters {
	if in == nil {
		return nil
	}
	out := new(SplitTunnelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitTunnelSpec) DeepCopyInto(out *SplitTunnelSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitTunnelSpec.
func (in *SplitTunnelSpec) DeepCopy() *SplitTunnelSpec {
	if in == nil {
		return nil
	}
	out := new(SplitTunnelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitTunnelStatus) DeepCopyInto(out *SplitTunnelStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitTunnelStatus.
func (in *SplitTunnelStatus) DeepCopy() *SplitTunnelStatus {
	if in == nil {
		return nil
	}
	out := new(SplitTunnelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelsInitParameters) DeepCopyInto(out *TunnelsInitParameters) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelsInitParameters.
func (in *TunnelsInitParameters) DeepCopy() *TunnelsInitParameters {
	if in == nil {
		return nil
	}
	out := new(TunnelsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelsObservation) DeepCopyInto(out *TunnelsObservation) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelsObservation.
func (in *TunnelsObservation) DeepCopy() *TunnelsObservation {
	if in == nil {
		return nil
	}
	out := new(TunnelsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelsParameters) DeepCopyInto(out *TunnelsParameters) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelsParameters.
func (in *TunnelsParameters) DeepCopy() *TunnelsParameters {
	if in == nil {
		return nil
	}
	out := new(TunnelsParameters)
	in.DeepCopyInto(out)
	return out
}
