
apiVersion: emailrouting.cloudflare.upbound.io/v1alpha1
kind: Settings
metadata:
  name: example
  labels:
    testing.cloudflare.upbound.io/require-zone: "true"
spec:
  forProvider:
    zoneIdRefs:
      name: example
    enabled: true
