apiVersion: apishield.cloudflare.upbound.io/v1alpha1
kind: APIShield
metadata:
  name: example-api-shield
  labels:
    testing.cloudflare.upbound.io/require-zone: "true"
spec:
  forProvider:
    zoneIdRef:
      name: example
    authIdCharacteristics:
      - name: my-example-header
        type: header
