apiVersion: account.cloudflare.upbound.io/v1alpha1
kind: APIToken
metadata:
  name: example-api-token
spec:
  forProvider:
    name: example-api-token
    policy:
      - permissionGroups:
          - 1a71c399035b4950a1bd1466bbe4f420
        resources:
          "com.cloudflare.api.account.*": "*"
  writeConnectionSecretToRef:
    name: example-api-token
    namespace: default
