apiVersion: access.cloudflare.upbound.io/v1alpha1
kind: Application
metadata:
  name: example-access-application
  labels:
    testing.cloudflare.upbound.io/require-zone: "true"
  annotations:
    uptest.upbound.io/pre-delete-hook: ../../cluster/test/cleanup-children.sh access-application
spec:
  forProvider:
    zoneIdRef:
      name: example
    name: staging application
    domain: staging.cloudflare-test-enterprise.crossplane.io
    type: self_hosted
    sessionDuration: 24h
    corsHeaders:
      - allowedMethods:
          - GET
          - POST
          - OPTIONS
        allowedOrigins:
          - https://example.com
        allowCredentials: true
        maxAge: 10
